// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cid_sweep.sql

package queries

import (
	"context"
)

const countCIDAliasReferences = `-- name: CountCIDAliasReferences :one
SELECT COUNT(*)
FROM file
WHERE "externalID" = $1
`

func (q *Queries) CountCIDAliasReferences(ctx context.Context, exactAlias string) (int64, error) {
	row := q.db.QueryRow(ctx, countCIDAliasReferences, exactAlias)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCIDCandidates = `-- name: ListCIDCandidates :many
SELECT "externalID", COUNT(*) AS reference_count
FROM file
WHERE "externalID" ~ '^Qm[1-9A-HJ-NP-Za-km-z]{44}$'
GROUP BY "externalID"
ORDER BY "externalID"
`

type ListCIDCandidatesRow struct {
	ExternalID     string `json:"externalID"`
	ReferenceCount int64  `json:"reference_count"`
}

func (q *Queries) ListCIDCandidates(ctx context.Context) ([]ListCIDCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCIDCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCIDCandidatesRow{}
	for rows.Next() {
		var i ListCIDCandidatesRow
		if err := rows.Scan(&i.ExternalID, &i.ReferenceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCIDCaseAliases = `-- name: ListCIDCaseAliases :many
SELECT "externalID", COUNT(*) AS reference_count
FROM file
WHERE char_length("externalID") = 64
  AND "externalID" ~ '^[0-9A-Fa-f]{64}$'
  AND "externalID" <> lower("externalID")
GROUP BY "externalID"
ORDER BY "externalID"
`

type ListCIDCaseAliasesRow struct {
	ExternalID     string `json:"externalID"`
	ReferenceCount int64  `json:"reference_count"`
}

func (q *Queries) ListCIDCaseAliases(ctx context.Context) ([]ListCIDCaseAliasesRow, error) {
	rows, err := q.db.Query(ctx, listCIDCaseAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCIDCaseAliasesRow{}
	for rows.Next() {
		var i ListCIDCaseAliasesRow
		if err := rows.Scan(&i.ExternalID, &i.ReferenceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCIDGroup = `-- name: UpdateCIDGroup :execrows
UPDATE file
SET "externalID" = $1
WHERE "externalID" = ANY($2::text[])
  AND "externalID" <> $1
`

type UpdateCIDGroupParams struct {
	LowercaseTarget string   `json:"lowercase_target"`
	ExactAliases    []string `json:"exact_aliases"`
}

func (q *Queries) UpdateCIDGroup(ctx context.Context, arg UpdateCIDGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCIDGroup, arg.LowercaseTarget, arg.ExactAliases)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
