// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillContentMetadata = `-- name: BackfillContentMetadata :execrows
UPDATE file
SET content_metadata = $2
WHERE id = $1
  AND "externalID" = $3
  AND content_metadata = '{}'::jsonb
`

type BackfillContentMetadataParams struct {
	ID              pgtype.UUID `json:"id"`
	ContentMetadata []byte      `json:"content_metadata"`
	ExternalID      string      `json:"externalID"`
}

// Compare-and-set: only writes when content_metadata is still empty AND
// the row's externalID is the one we measured against. Protects against
// the lazy-backfill overwriting freshly-replaced content's metadata.
// Updates only content_metadata; does NOT bump version (FR-018).
func (q *Queries) BackfillContentMetadata(ctx context.Context, arg BackfillContentMetadataParams) (int64, error) {
	result, err := q.db.Exec(ctx, backfillContentMetadata, arg.ID, arg.ContentMetadata, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countDocumentsByExternalID = `-- name: CountDocumentsByExternalID :one
SELECT COUNT(*) FROM file WHERE "externalID" = $1
`

func (q *Queries) CountDocumentsByExternalID(ctx context.Context, externalid string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByExternalID, externalid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO file (id, "externalID", "mimeType", size, "displayName", "createdBy",
                      "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
                      "createdDate", "updatedDate", version, content_metadata, "externalReference")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 1, $13, $14)
RETURNING id
`

type CreateDocumentParams struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	ContentMetadata   []byte             `json:"content_metadata"`
	ExternalReference pgtype.Text        `json:"externalReference"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.ExternalID,
		arg.MimeType,
		arg.Size,
		arg.DisplayName,
		arg.CreatedBy,
		arg.TemporaryLocation,
		arg.StorageBucketId,
		arg.AuthorizationId,
		arg.TagsetId,
		arg.CreatedDate,
		arg.UpdatedDate,
		arg.ContentMetadata,
		arg.ExternalReference,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDocument = `-- name: DeleteDocument :one
DELETE FROM file
WHERE id = $1
RETURNING "externalID", "authorizationId", "tagsetId"
`

type DeleteDocumentRow struct {
	ExternalID      string      `json:"externalID"`
	AuthorizationId pgtype.UUID `json:"authorizationId"`
	TagsetId        pgtype.UUID `json:"tagsetId"`
}

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) (DeleteDocumentRow, error) {
	row := q.db.QueryRow(ctx, deleteDocument, id)
	var i DeleteDocumentRow
	err := row.Scan(&i.ExternalID, &i.AuthorizationId, &i.TagsetId)
	return i, err
}

const findDocumentByExternalIDAndBucket = `-- name: FindDocumentByExternalIDAndBucket :one
SELECT id, "externalID", "mimeType", size, "displayName", "createdBy",
       "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
       "createdDate", "updatedDate", version, content_metadata, "externalReference"
FROM file
WHERE "externalID" = $1 AND "storageBucketId" = $2 AND "externalReference" IS NULL
ORDER BY "createdDate" ASC, id ASC
LIMIT 1
`

type FindDocumentByExternalIDAndBucketParams struct {
	ExternalID      string      `json:"externalID"`
	StorageBucketId pgtype.UUID `json:"storageBucketId"`
}

type FindDocumentByExternalIDAndBucketRow struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
	ContentMetadata   []byte             `json:"content_metadata"`
	ExternalReference pgtype.Text        `json:"externalReference"`
}

// Content-dedup lookup for PLAIN (non-reference) uploads only. The
// "externalReference" IS NULL filter is the keystone of the dual-identity
// rule: reference-bearing rows are identity'd by their externalReference, so
// a plain upload must never dedup onto (and thus couple its lifecycle to) a
// reference-bearing row that happens to share the same bytes. Plain rows
// dedup among plain rows; reference rows are resolved by reference.
// Deterministic selection: oldest row wins. Matters if historical duplicates
// exist (pre-migration) or if two racing inserts both succeed (prod has no
// externalID unique index). "createdDate" ASC, then id ASC as tiebreaker.
func (q *Queries) FindDocumentByExternalIDAndBucket(ctx context.Context, arg FindDocumentByExternalIDAndBucketParams) (FindDocumentByExternalIDAndBucketRow, error) {
	row := q.db.QueryRow(ctx, findDocumentByExternalIDAndBucket, arg.ExternalID, arg.StorageBucketId)
	var i FindDocumentByExternalIDAndBucketRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.MimeType,
		&i.Size,
		&i.DisplayName,
		&i.CreatedBy,
		&i.TemporaryLocation,
		&i.StorageBucketId,
		&i.AuthorizationId,
		&i.TagsetId,
		&i.CreatedDate,
		&i.UpdatedDate,
		&i.Version,
		&i.ContentMetadata,
		&i.ExternalReference,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, "externalID", "mimeType", size, "displayName", "createdBy",
       "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
       "createdDate", "updatedDate", version, content_metadata, "externalReference"
FROM file
WHERE id = $1
`

type GetDocumentByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
	ContentMetadata   []byte             `json:"content_metadata"`
	ExternalReference pgtype.Text        `json:"externalReference"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (GetDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.MimeType,
		&i.Size,
		&i.DisplayName,
		&i.CreatedBy,
		&i.TemporaryLocation,
		&i.StorageBucketId,
		&i.AuthorizationId,
		&i.TagsetId,
		&i.CreatedDate,
		&i.UpdatedDate,
		&i.Version,
		&i.ContentMetadata,
		&i.ExternalReference,
	)
	return i, err
}

const getDocumentByReference = `-- name: GetDocumentByReference :one
SELECT id, "externalID", "mimeType", size, "displayName", "createdBy",
       "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
       "createdDate", "updatedDate", version, content_metadata, "externalReference"
FROM file
WHERE "externalReference" = $1
ORDER BY "createdDate" ASC, id ASC
LIMIT 1
`

type GetDocumentByReferenceRow struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
	ContentMetadata   []byte             `json:"content_metadata"`
	ExternalReference pgtype.Text        `json:"externalReference"`
}

// Global by-reference lookup (provider fetch): resolves an opaque
// externalReference across ALL buckets. Several buckets may carry the same
// reference (re-share, one shared blob); oldest row wins deterministically.
func (q *Queries) GetDocumentByReference(ctx context.Context, externalreference pgtype.Text) (GetDocumentByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByReference, externalreference)
	var i GetDocumentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.MimeType,
		&i.Size,
		&i.DisplayName,
		&i.CreatedBy,
		&i.TemporaryLocation,
		&i.StorageBucketId,
		&i.AuthorizationId,
		&i.TagsetId,
		&i.CreatedDate,
		&i.UpdatedDate,
		&i.Version,
		&i.ContentMetadata,
		&i.ExternalReference,
	)
	return i, err
}

const getDocumentByReferenceInBucket = `-- name: GetDocumentByReferenceInBucket :one
SELECT id, "externalID", "mimeType", size, "displayName", "createdBy",
       "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
       "createdDate", "updatedDate", version, content_metadata, "externalReference"
FROM file
WHERE "externalReference" = $1 AND "storageBucketId" = $2
ORDER BY "createdDate" ASC, id ASC
LIMIT 1
`

type GetDocumentByReferenceInBucketParams struct {
	ExternalReference pgtype.Text `json:"externalReference"`
	StorageBucketId   pgtype.UUID `json:"storageBucketId"`
}

type GetDocumentByReferenceInBucketRow struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
	ContentMetadata   []byte             `json:"content_metadata"`
	ExternalReference pgtype.Text        `json:"externalReference"`
}

// Bucket-scoped by-reference lookup (read resolution): the single document
// carrying this reference in the given bucket. The partial
// UNIQUE(externalReference, storageBucketId) normally guarantees at most one
// match; ORDER BY "createdDate" ASC, id ASC keeps resolution deterministic
// (oldest wins) as defense-in-depth, matching the global by-reference query,
// even if that constraint were ever absent.
func (q *Queries) GetDocumentByReferenceInBucket(ctx context.Context, arg GetDocumentByReferenceInBucketParams) (GetDocumentByReferenceInBucketRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByReferenceInBucket, arg.ExternalReference, arg.StorageBucketId)
	var i GetDocumentByReferenceInBucketRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.MimeType,
		&i.Size,
		&i.DisplayName,
		&i.CreatedBy,
		&i.TemporaryLocation,
		&i.StorageBucketId,
		&i.AuthorizationId,
		&i.TagsetId,
		&i.CreatedDate,
		&i.UpdatedDate,
		&i.Version,
		&i.ContentMetadata,
		&i.ExternalReference,
	)
	return i, err
}

const listDocumentsByMimeTypes = `-- name: ListDocumentsByMimeTypes :many
SELECT id, "externalID", "mimeType", size, "displayName"
FROM file
WHERE "mimeType" = ANY($1::text[])
ORDER BY "createdDate" ASC
`

type ListDocumentsByMimeTypesRow struct {
	ID          pgtype.UUID `json:"id"`
	ExternalID  string      `json:"externalID"`
	MimeType    string      `json:"mimeType"`
	Size        int32       `json:"size"`
	DisplayName string      `json:"displayName"`
}

// Repair-job scan (spec 019): rows whose stored type is one of the given
// (generic) MIME types. Office-extension filtering happens in the domain
// layer, which owns the office vocabulary.
func (q *Queries) ListDocumentsByMimeTypes(ctx context.Context, dollar_1 []string) ([]ListDocumentsByMimeTypesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByMimeTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsByMimeTypesRow{}
	for rows.Next() {
		var i ListDocumentsByMimeTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.MimeType,
			&i.Size,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentFile = `-- name: UpdateDocumentFile :one
UPDATE file
SET "externalID" = $2, "mimeType" = $3, size = $4, "updatedDate" = $5,
    content_metadata = $6
WHERE id = $1
RETURNING "temporaryLocation"
`

type UpdateDocumentFileParams struct {
	ID              pgtype.UUID        `json:"id"`
	ExternalID      string             `json:"externalID"`
	MimeType        string             `json:"mimeType"`
	Size            int32              `json:"size"`
	UpdatedDate     pgtype.Timestamptz `json:"updatedDate"`
	ContentMetadata []byte             `json:"content_metadata"`
}

// Updates content fields. content_metadata replaces any prior value (Replace
// emits fresh dims via Process; the old row's content_metadata is discarded).
//
// RETURNING "temporaryLocation" is the AUTHORITATIVE in-tx durability state of the
// row read while it is UPDATE-locked in this transaction. The transactional
// backup-outbox producer enqueues the new content hash ONLY when this is false
// (durable): a content-replace that loaded the doc as temporary can race a
// concurrent temp→durable PATCH that commits FIRST, so the pre-loaded snapshot is
// stale; deciding the enqueue from this locked-row flag (never the snapshot) closes
// the stranded-blob race in both orderings — replace-before-flip (temporary → no
// enqueue, the flip's own outbox row covers the then-current hash) and
// flip-before-replace (durable → the replace enqueues the new hash). 0 rows
// (missing row) → no row returned (pgx.ErrNoRows) → model.ErrDocumentNotFound.
func (q *Queries) UpdateDocumentFile(ctx context.Context, arg UpdateDocumentFileParams) (bool, error) {
	row := q.db.QueryRow(ctx, updateDocumentFile,
		arg.ID,
		arg.ExternalID,
		arg.MimeType,
		arg.Size,
		arg.UpdatedDate,
		arg.ContentMetadata,
	)
	var temporaryLocation bool
	err := row.Scan(&temporaryLocation)
	return temporaryLocation, err
}

const updateDocumentMetadata = `-- name: UpdateDocumentMetadata :one
UPDATE file
SET "storageBucketId"    = $2,
    "temporaryLocation"  = $3,
    "displayName"        = $4,
    "authorizationId"    = $5,
    "createdBy"          = $6,
    "externalReference"  = $7,
    "updatedDate"        = $8,
    version              = version + 1
WHERE id = $1 AND version = $9
RETURNING id, "externalID", "mimeType", size, "displayName", "createdBy",
          "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
          "createdDate", "updatedDate", version, content_metadata, "externalReference"
`

type UpdateDocumentMetadataParams struct {
	ID                pgtype.UUID        `json:"id"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	DisplayName       string             `json:"displayName"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	ExternalReference pgtype.Text        `json:"externalReference"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
}

type UpdateDocumentMetadataRow struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
	ContentMetadata   []byte             `json:"content_metadata"`
	ExternalReference pgtype.Text        `json:"externalReference"`
}

// Updates the mutable metadata fields atomically with optimistic locking.
// Caller fills unchanged fields with their current values. This is the
// "move + re-attribute" primitive: besides storageBucketId/temporaryLocation/
// displayName it also re-points authorizationId, createdBy, and the opaque
// externalReference. mimeType, externalID, size are not mutable here — they
// change only via UpdateDocumentFile.
//
// RETURNING the FULL row (mirrors GetDocumentByID's column list) yields the
// AUTHORITATIVE post-update document read while the row is UPDATE-locked in this
// transaction — the applied metadata SETs AND any concurrent content-replace
// already committed. The service maps it ONCE (documentFromRow) and builds the
// ENTIRE PATCH response from it, so externalID/size can never disagree with
// content_metadata/dims (a concurrent replace swaps externalID/size + dims
// WITHOUT bumping version; sourcing every field from this one locked row keeps
// them consistent). The transactional backup-outbox producer enqueues the same
// row's externalID/size, never a handler-threaded snapshot. 0 rows (version
// mismatch / missing row) → no row returned (pgx.ErrNoRows), which the adapter
// maps to model.ErrDocumentNotFound.
func (q *Queries) UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) (UpdateDocumentMetadataRow, error) {
	row := q.db.QueryRow(ctx, updateDocumentMetadata,
		arg.ID,
		arg.StorageBucketId,
		arg.TemporaryLocation,
		arg.DisplayName,
		arg.AuthorizationId,
		arg.CreatedBy,
		arg.ExternalReference,
		arg.UpdatedDate,
		arg.Version,
	)
	var i UpdateDocumentMetadataRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.MimeType,
		&i.Size,
		&i.DisplayName,
		&i.CreatedBy,
		&i.TemporaryLocation,
		&i.StorageBucketId,
		&i.AuthorizationId,
		&i.TagsetId,
		&i.CreatedDate,
		&i.UpdatedDate,
		&i.Version,
		&i.ContentMetadata,
		&i.ExternalReference,
	)
	return i, err
}

const updateDocumentMimeType = `-- name: UpdateDocumentMimeType :execrows
UPDATE file
SET "mimeType"    = $2,
    "updatedDate" = $3,
    version       = version + 1
WHERE id = $1
  AND "externalID" = $4
`

type UpdateDocumentMimeTypeParams struct {
	ID          pgtype.UUID        `json:"id"`
	MimeType    string             `json:"mimeType"`
	UpdatedDate pgtype.Timestamptz `json:"updatedDate"`
	ExternalID  string             `json:"externalID"`
}

// Repair-job relabel (spec 019): corrects only the stored MIME type.
// Deliberately narrow — content fields change exclusively via
// UpdateDocumentFile. Compare-and-set on externalID: the relabel applies
// only if the content is still the one the repair job sniffed, protecting
// against a concurrent Replace (which already set the correct MIME type)
// landing between the suspect scan and this write.
func (q *Queries) UpdateDocumentMimeType(ctx context.Context, arg UpdateDocumentMimeTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentMimeType,
		arg.ID,
		arg.MimeType,
		arg.UpdatedDate,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
