// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillContentMetadata = `-- name: BackfillContentMetadata :execrows
UPDATE file
SET content_metadata = $2
WHERE id = $1
  AND "externalID" = $3
  AND content_metadata = '{}'::jsonb
`

type BackfillContentMetadataParams struct {
	ID              pgtype.UUID `json:"id"`
	ContentMetadata []byte      `json:"content_metadata"`
	ExternalID      string      `json:"externalID"`
}

// Compare-and-set: only writes when content_metadata is still empty AND
// the row's externalID is the one we measured against. Protects against
// the dimension sweep overwriting freshly-replaced content's metadata.
// Updates only content_metadata; does NOT bump version (FR-018).
func (q *Queries) BackfillContentMetadata(ctx context.Context, arg BackfillContentMetadataParams) (int64, error) {
	result, err := q.db.Exec(ctx, backfillContentMetadata, arg.ID, arg.ContentMetadata, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countDocumentsByExternalID = `-- name: CountDocumentsByExternalID :one
SELECT COUNT(*) FROM file WHERE "externalID" = $1
`

func (q *Queries) CountDocumentsByExternalID(ctx context.Context, externalid string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByExternalID, externalid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO file (id, "externalID", "mimeType", size, "displayName", "createdBy",
                      "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
                      "createdDate", "updatedDate", version, content_metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 1, $13)
RETURNING id
`

type CreateDocumentParams struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	ContentMetadata   []byte             `json:"content_metadata"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.ExternalID,
		arg.MimeType,
		arg.Size,
		arg.DisplayName,
		arg.CreatedBy,
		arg.TemporaryLocation,
		arg.StorageBucketId,
		arg.AuthorizationId,
		arg.TagsetId,
		arg.CreatedDate,
		arg.UpdatedDate,
		arg.ContentMetadata,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDocument = `-- name: DeleteDocument :one
DELETE FROM file
WHERE id = $1
RETURNING "externalID", "authorizationId", "tagsetId"
`

type DeleteDocumentRow struct {
	ExternalID      string      `json:"externalID"`
	AuthorizationId pgtype.UUID `json:"authorizationId"`
	TagsetId        pgtype.UUID `json:"tagsetId"`
}

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) (DeleteDocumentRow, error) {
	row := q.db.QueryRow(ctx, deleteDocument, id)
	var i DeleteDocumentRow
	err := row.Scan(&i.ExternalID, &i.AuthorizationId, &i.TagsetId)
	return i, err
}

const findDocumentByExternalIDAndBucket = `-- name: FindDocumentByExternalIDAndBucket :one
SELECT id, "externalID", "mimeType", size, "displayName", "createdBy",
       "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
       "createdDate", "updatedDate", version, content_metadata
FROM file
WHERE "externalID" = $1 AND "storageBucketId" = $2
ORDER BY "createdDate" ASC, id ASC
LIMIT 1
`

type FindDocumentByExternalIDAndBucketParams struct {
	ExternalID      string      `json:"externalID"`
	StorageBucketId pgtype.UUID `json:"storageBucketId"`
}

type FindDocumentByExternalIDAndBucketRow struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
	ContentMetadata   []byte             `json:"content_metadata"`
}

// Deterministic selection: oldest row wins. Matters if historical duplicates
// exist (pre-migration) or if two racing inserts both succeed before the
// unique index lands in prod. "createdDate" ASC, then id ASC as tiebreaker.
func (q *Queries) FindDocumentByExternalIDAndBucket(ctx context.Context, arg FindDocumentByExternalIDAndBucketParams) (FindDocumentByExternalIDAndBucketRow, error) {
	row := q.db.QueryRow(ctx, findDocumentByExternalIDAndBucket, arg.ExternalID, arg.StorageBucketId)
	var i FindDocumentByExternalIDAndBucketRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.MimeType,
		&i.Size,
		&i.DisplayName,
		&i.CreatedBy,
		&i.TemporaryLocation,
		&i.StorageBucketId,
		&i.AuthorizationId,
		&i.TagsetId,
		&i.CreatedDate,
		&i.UpdatedDate,
		&i.Version,
		&i.ContentMetadata,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, "externalID", "mimeType", size, "displayName", "createdBy",
       "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
       "createdDate", "updatedDate", version, content_metadata
FROM file
WHERE id = $1
`

type GetDocumentByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
	ContentMetadata   []byte             `json:"content_metadata"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (GetDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.MimeType,
		&i.Size,
		&i.DisplayName,
		&i.CreatedBy,
		&i.TemporaryLocation,
		&i.StorageBucketId,
		&i.AuthorizationId,
		&i.TagsetId,
		&i.CreatedDate,
		&i.UpdatedDate,
		&i.Version,
		&i.ContentMetadata,
	)
	return i, err
}

const listDocumentsByMimeTypes = `-- name: ListDocumentsByMimeTypes :many
SELECT id, "externalID", "mimeType", size, "displayName"
FROM file
WHERE "mimeType" = ANY($1::text[])
ORDER BY "createdDate" ASC
`

type ListDocumentsByMimeTypesRow struct {
	ID          pgtype.UUID `json:"id"`
	ExternalID  string      `json:"externalID"`
	MimeType    string      `json:"mimeType"`
	Size        int32       `json:"size"`
	DisplayName string      `json:"displayName"`
}

// Repair-job scan (spec 019): rows whose stored type is one of the given
// (generic) MIME types. Office-extension filtering happens in the domain
// layer, which owns the office vocabulary.
func (q *Queries) ListDocumentsByMimeTypes(ctx context.Context, dollar_1 []string) ([]ListDocumentsByMimeTypesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByMimeTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsByMimeTypesRow{}
	for rows.Next() {
		var i ListDocumentsByMimeTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.MimeType,
			&i.Size,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesNeedingDims = `-- name: ListImagesNeedingDims :many
SELECT id, "externalID", "mimeType"
FROM file
WHERE "mimeType" LIKE 'image/%'
  AND content_metadata = '{}'::jsonb
  AND id > $1
ORDER BY id
LIMIT $2
`

type ListImagesNeedingDimsParams struct {
	ID    pgtype.UUID `json:"id"`
	Limit int32       `json:"limit"`
}

type ListImagesNeedingDimsRow struct {
	ID         pgtype.UUID `json:"id"`
	ExternalID string      `json:"externalID"`
	MimeType   string      `json:"mimeType"`
}

// Paged scan for the image-dimension backfill sweep (the sweep-dims job, spec 019/020): image rows whose
// content_metadata is still unpopulated ('{}'). Keyset-paged by id ($1 = cursor, $2 = page size) so
// a large first-run legacy set never loads whole. The sweep reads each blob by externalID, does a
// header-only measure, and compare-and-sets the dims via BackfillContentMetadata.
// `file.id` is the primary key, so its B-tree index supports both `id > cursor` and ORDER BY id;
// each row is visited at most once during this finite manual sweep. A separate schema migration
// and partial index would add steady-state write cost for an operation intended to converge away.
func (q *Queries) ListImagesNeedingDims(ctx context.Context, arg ListImagesNeedingDimsParams) ([]ListImagesNeedingDimsRow, error) {
	rows, err := q.db.Query(ctx, listImagesNeedingDims, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImagesNeedingDimsRow{}
	for rows.Next() {
		var i ListImagesNeedingDimsRow
		if err := rows.Scan(&i.ID, &i.ExternalID, &i.MimeType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentFile = `-- name: UpdateDocumentFile :execrows
UPDATE file
SET "externalID" = $2, "mimeType" = $3, size = $4, "updatedDate" = $5,
    content_metadata = $6, version = version + 1
WHERE id = $1 AND "externalID" = $7 AND version = $8
`

type UpdateDocumentFileParams struct {
	ID              pgtype.UUID        `json:"id"`
	ExternalID      string             `json:"externalID"`
	MimeType        string             `json:"mimeType"`
	Size            int32              `json:"size"`
	UpdatedDate     pgtype.Timestamptz `json:"updatedDate"`
	ContentMetadata []byte             `json:"content_metadata"`
	ExternalID_2    string             `json:"externalID_2"`
	Version         int32              `json:"version"`
}

// Updates content fields. content_metadata replaces any prior value (Replace
// emits fresh dims via Process; the old row's content_metadata is discarded).
// Compare-and-set on both the externalID and version the caller read before
// streaming, and bump version on success. This serializes content replacement
// with metadata updates (especially temporary→permanent promotion): neither may
// commit based on stale routing state and thereby miss or misroute an outbox hint.
func (q *Queries) UpdateDocumentFile(ctx context.Context, arg UpdateDocumentFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentFile,
		arg.ID,
		arg.ExternalID,
		arg.MimeType,
		arg.Size,
		arg.UpdatedDate,
		arg.ContentMetadata,
		arg.ExternalID_2,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocumentMetadata = `-- name: UpdateDocumentMetadata :execrows
UPDATE file
SET "storageBucketId"    = $2,
    "temporaryLocation"  = $3,
    "displayName"        = $4,
    "updatedDate"        = $5,
    version              = version + 1
WHERE id = $1 AND version = $6
`

type UpdateDocumentMetadataParams struct {
	ID                pgtype.UUID        `json:"id"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	DisplayName       string             `json:"displayName"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
}

// Updates the mutable metadata fields (storageBucketId, temporaryLocation,
// displayName) atomically with optimistic locking. Caller fills unchanged
// fields with their current values. mimeType, externalID, size are not
// mutable through this query — they change only via UpdateDocumentFile.
func (q *Queries) UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentMetadata,
		arg.ID,
		arg.StorageBucketId,
		arg.TemporaryLocation,
		arg.DisplayName,
		arg.UpdatedDate,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocumentMimeType = `-- name: UpdateDocumentMimeType :execrows
UPDATE file
SET "mimeType"    = $2,
    "updatedDate" = $3,
    version       = version + 1
WHERE id = $1
  AND "externalID" = $4
`

type UpdateDocumentMimeTypeParams struct {
	ID          pgtype.UUID        `json:"id"`
	MimeType    string             `json:"mimeType"`
	UpdatedDate pgtype.Timestamptz `json:"updatedDate"`
	ExternalID  string             `json:"externalID"`
}

// Repair-job relabel (spec 019): corrects only the stored MIME type.
// Deliberately narrow — content fields change exclusively via
// UpdateDocumentFile. Compare-and-set on externalID: the relabel applies
// only if the content is still the one the repair job sniffed, protecting
// against a concurrent Replace (which already set the correct MIME type)
// landing between the suspect scan and this write.
func (q *Queries) UpdateDocumentMimeType(ctx context.Context, arg UpdateDocumentMimeTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentMimeType,
		arg.ID,
		arg.MimeType,
		arg.UpdatedDate,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
