// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocumentsByExternalID = `-- name: CountDocumentsByExternalID :one
SELECT COUNT(*) FROM file WHERE "externalID" = $1
`

func (q *Queries) CountDocumentsByExternalID(ctx context.Context, externalid string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByExternalID, externalid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO file (id, "externalID", "mimeType", size, "displayName", "createdBy",
                      "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
                      "createdDate", "updatedDate", version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 1)
RETURNING id
`

type CreateDocumentParams struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.ExternalID,
		arg.MimeType,
		arg.Size,
		arg.DisplayName,
		arg.CreatedBy,
		arg.TemporaryLocation,
		arg.StorageBucketId,
		arg.AuthorizationId,
		arg.TagsetId,
		arg.CreatedDate,
		arg.UpdatedDate,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDocument = `-- name: DeleteDocument :one
DELETE FROM file
WHERE id = $1
RETURNING "externalID", "authorizationId", "tagsetId"
`

type DeleteDocumentRow struct {
	ExternalID      string      `json:"externalID"`
	AuthorizationId pgtype.UUID `json:"authorizationId"`
	TagsetId        pgtype.UUID `json:"tagsetId"`
}

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) (DeleteDocumentRow, error) {
	row := q.db.QueryRow(ctx, deleteDocument, id)
	var i DeleteDocumentRow
	err := row.Scan(&i.ExternalID, &i.AuthorizationId, &i.TagsetId)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, "externalID", "mimeType", size, "displayName", "createdBy",
       "temporaryLocation", "storageBucketId", "authorizationId", "tagsetId",
       "createdDate", "updatedDate", version
FROM file
WHERE id = $1
`

type GetDocumentByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalID        string             `json:"externalID"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	DisplayName       string             `json:"displayName"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (GetDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.MimeType,
		&i.Size,
		&i.DisplayName,
		&i.CreatedBy,
		&i.TemporaryLocation,
		&i.StorageBucketId,
		&i.AuthorizationId,
		&i.TagsetId,
		&i.CreatedDate,
		&i.UpdatedDate,
		&i.Version,
	)
	return i, err
}

const updateDocumentFile = `-- name: UpdateDocumentFile :execrows
UPDATE file
SET "externalID" = $2, "mimeType" = $3, size = $4, "updatedDate" = $5
WHERE id = $1
`

type UpdateDocumentFileParams struct {
	ID          pgtype.UUID        `json:"id"`
	ExternalID  string             `json:"externalID"`
	MimeType    string             `json:"mimeType"`
	Size        int32              `json:"size"`
	UpdatedDate pgtype.Timestamptz `json:"updatedDate"`
}

func (q *Queries) UpdateDocumentFile(ctx context.Context, arg UpdateDocumentFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentFile,
		arg.ID,
		arg.ExternalID,
		arg.MimeType,
		arg.Size,
		arg.UpdatedDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocumentLocation = `-- name: UpdateDocumentLocation :execrows
UPDATE file
SET "storageBucketId" = $2, "temporaryLocation" = $3, "updatedDate" = $4, version = version + 1
WHERE id = $1 AND version = $5
`

type UpdateDocumentLocationParams struct {
	ID                pgtype.UUID        `json:"id"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
}

func (q *Queries) UpdateDocumentLocation(ctx context.Context, arg UpdateDocumentLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentLocation,
		arg.ID,
		arg.StorageBucketId,
		arg.TemporaryLocation,
		arg.UpdatedDate,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
