// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID                pgtype.UUID        `json:"id"`
	CreatedDate       pgtype.Timestamptz `json:"createdDate"`
	UpdatedDate       pgtype.Timestamptz `json:"updatedDate"`
	Version           int32              `json:"version"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	DisplayName       string             `json:"displayName"`
	MimeType          string             `json:"mimeType"`
	Size              int32              `json:"size"`
	ExternalID        string             `json:"externalID"`
	TemporaryLocation bool               `json:"temporaryLocation"`
	AuthorizationId   pgtype.UUID        `json:"authorizationId"`
	StorageBucketId   pgtype.UUID        `json:"storageBucketId"`
	TagsetId          pgtype.UUID        `json:"tagsetId"`
	ContentMetadata   []byte             `json:"content_metadata"`
}

type FileBackupOutbox struct {
	ID          int64              `json:"id"`
	FileId      pgtype.UUID        `json:"fileId"`
	ExternalID  string             `json:"externalID"`
	Priority    int16              `json:"priority"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	Deliveries  int32              `json:"deliveries"`
	LastError   pgtype.Text        `json:"lastError"`
	CreatedBy   pgtype.UUID        `json:"createdBy"`
	CreatedDate pgtype.Timestamptz `json:"createdDate"`
	Size        int64              `json:"size"`
	ClaimedAt   pgtype.Timestamptz `json:"claimedAt"`
	VisibleAt   pgtype.Timestamptz `json:"visibleAt"`
}
