// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBackupOutboxPendingByHash = `-- name: DeleteBackupOutboxPendingByHash :execrows
DELETE FROM file_backup_outbox
WHERE "externalID" = $1 AND status = 'pending'
`

// Orphan hygiene: when the LAST file row referencing a blob is deleted and the blob itself is
// removed (refcount→0), any still-pending outbox row for that hash points at bytes that no
// longer exist — the consumer's fetch could only ever 404. file-service is the one deleting the
// blob, so it removes the dead hint too (master-of-orphans). in_progress rows are left to the
// consumer's own 404→skip backstop; done/skipped/dead_letter are history, untouched.
func (q *Queries) DeleteBackupOutboxPendingByHash(ctx context.Context, externalid string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackupOutboxPendingByHash, externalid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueBackupOutbox = `-- name: EnqueueBackupOutbox :exec

INSERT INTO file_backup_outbox ("fileId", "externalID", priority, "createdBy", "createdDate", size)
VALUES ($1, $2, $3, $4, $5, $6)
`

type EnqueueBackupOutboxParams struct {
	FileId      pgtype.UUID        `json:"fileId"`
	ExternalID  string             `json:"externalID"`
	Priority    int16              `json:"priority"`
	CreatedBy   pgtype.UUID        `json:"createdBy"`
	CreatedDate pgtype.Timestamptz `json:"createdDate"`
	Size        int64              `json:"size"`
}

// file-service is the outbox DML owner (008-continuous-file-backup). The INSERT runs INSIDE
// the same transaction as the `file` row (FR-001: write-then-record; no committed outbox
// entry without a file row). The consumer (file-backup-service) reads/claims via a scoped role.
// Record a content-hash backup hint for a newly stored/replaced object.
func (q *Queries) EnqueueBackupOutbox(ctx context.Context, arg EnqueueBackupOutboxParams) error {
	_, err := q.db.Exec(ctx, enqueueBackupOutbox,
		arg.FileId,
		arg.ExternalID,
		arg.Priority,
		arg.CreatedBy,
		arg.CreatedDate,
		arg.Size,
	)
	return err
}

const pruneBackupOutboxDone = `-- name: PruneBackupOutboxDone :execrows
DELETE FROM file_backup_outbox
WHERE status = 'done' AND "createdDate" < $1
`

// Keep the outbox bounded (SC-008): drop rows the consumer already finished (status='done')
// older than a retention cutoff. The ledger (file-backup-service's own DB) keeps the durable
// record. Only 'done' is pruned — pending/in_progress/dead_letter/skipped are retained.
func (q *Queries) PruneBackupOutboxDone(ctx context.Context, createddate pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneBackupOutboxDone, createddate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
